language: ruby
rvm: 
    - 2.2.2
script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake db:migrate
    - bundle exec rspec spec/
    - rake test
before_script:
    - cd veraneio
